# Multi-source Flux Synchronization Manifest
---
# 1. External Source: Boutique Application Repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: boutique-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: Sandeep/BoutiqueCoupon
  # Removed secretRef here
  url: https://github.com/Shiv0388/microservices-demo.git

---
# 2. Deploy Boutique Application Manifests
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: boutique-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes-manifests
  prune: true
  targetNamespace: boutique
  sourceRef:
    kind: GitRepository
    name: boutique-source
