apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod

resources:
  - namespace.yaml
  - ../../base
  - canary.yaml

patches:
  - path: replica-patch.yaml

images:
  - name: nginx
    newTag: 1.27

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nginx-config
    literals:
      - ENV=prod
      - LOG_LEVEL=info