apiVersion: v2
name: cavisson-platform
description: A Helm chart for deploying Cavisson Platform on Kubernetes (per-tenant deployment)
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - cavisson
  - testing
  - performance
  - kubernetes
maintainers:
  - name: Cavisson Systems
    email: support@cavisson.com
