apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cavisson-platform
  namespace: cavisson-tenant1

spec:
  interval: 1m

  install:
    createNamespace: true
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  chart:
    spec:
      chart: cavisson-platform
      version: "4.15.1-B0"

      sourceRef:
        kind: HelmRepository
        name: artifact-keeper-platform
        namespace: flux-system
  
  values:
    persistence:
      primary:
        accessMode: ReadWriteMany
        storageClass: azurefile-csi
        size: 100Gi
    mongo:
      persistence:
        accessMode: ReadWriteOnce
        storageClass: managed-csi
    postgres:
      env:
        - name: POSTGRES_DB
          value: test
        - name: POSTGRES_USER
          value: cavisson
        - name: POSTGRES_PASSWORD
          value: cavisson
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      persistence:
        accessMode: ReadWriteOnce
        storageClass: managed-csi
    redis:
      persistence:
        storageClass: managed-csi
    image:
      repository: cloud-build.cav-test.com/cavisson-platform
      tag: "4.15.1.B0"

    imagePullSecrets:
      - name: artifact-keeper-auth