---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: microservices-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: Sandeep/BoutiqueCoupon

  url: https://github.com/Shiv0308/microservices-demo/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: boutique-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes-manifests
  prune: true
  targetNamespace: boutique
  sourceRef:
    kind: GitRepository
    name: microservices-demo

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-personal-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main

  url: https://github.com/dileep165794/flux-cd.git

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: boutique-canary
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/boutique
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-personal-source
  dependsOn:
    - name: boutique-apps