apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: boutique-frontend
  namespace: boutique-frontend
spec:
  interval: 5m
  url: https://github.com/Shiv0308/microservices-demo.git
  ref:
    branch: helm/Test
