apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-test-1790969728562-boutiquetest
  namespace: flux-system
spec:
  interval: 5m
  path: apps/demo-test-1790969728562/services/boutiquetest
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
