{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cavisson-platform.fullname" . }}-mongo
  labels:
    {{- include "cavisson-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  serviceName: {{ include "cavisson-platform.fullname" . }}-mongo
  replicas: 1
  selector:
    matchLabels:
      {{- include "cavisson-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongo
  template:
    metadata:
      labels:
        {{- include "cavisson-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
        env:
        {{- toYaml .Values.mongo.env | nindent 8 }}
        volumeMounts:
        {{- if .Values.mongo.persistence.enabled }}
        - name: mongo-data
          mountPath: /data/db
        {{- end }}
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
  {{- if .Values.mongo.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
        - {{ .Values.mongo.persistence.accessMode }}
      {{- if .Values.mongo.persistence.storageClass }}
      storageClassName: {{ .Values.mongo.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.mongo.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cavisson-platform.fullname" . }}-mongo
  labels:
    {{- include "cavisson-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: mongo
    protocol: TCP
    name: mongo
  selector:
    {{- include "cavisson-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
{{- end }}
