{{- if .Values.persistence.primary.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.primary.name }}
  labels:
    {{- include "cavisson-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.primary.accessMode }}
  {{- if .Values.persistence.primary.storageClass }}
  storageClassName: {{ .Values.persistence.primary.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.primary.size }}
{{- end }}
---
{{- if .Values.persistence.secondary.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.secondary.name }}
  labels:
    {{- include "cavisson-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.secondary.accessMode }}
  {{- if .Values.persistence.secondary.storageClass }}
  storageClassName: {{ .Values.persistence.secondary.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.secondary.size }}
{{- end }}
