apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: artifact-keeper-operator
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://cloud-build.cav-test.com/cavisson-operator-helm
  secretRef:
    name: artifact-keeper-auth      # ← same secret your platform repo uses
  # secretRef:
  #   name: artifact-keeper-auth     # uncomment if your registry needs auth
                                     # repo shows "Public" in your screenshot,
                                     # so probably not needed