apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cavisson-operator
  namespace: cavisson-operator

spec:
  interval: 1m

  install:
    createNamespace: true
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  chart:
    spec:
      chart: cavisson-operator
      version: "4.15.0-B0"

      sourceRef:
        kind: HelmRepository
        name: artifact-keeper-operator
        namespace: flux-system

  values:
    image:
      repository: cloud-build.cav-test.com/cavisson-operator
      tag: "4.15.0.B0"

    imagePullSecrets:
      - name: artifact-keeper-auth