apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: frontend
  namespace: helm-test-dev-1790852789807
spec:
  interval: 5m
  url: https://github.com/Shiv0308/microservices-demo.git
  ref:
    branch: helm/Test
